# Generated by Django 5.1.3 on 2024-11-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Высота коробки (м)'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='length',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Длина коробки (м)'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Вес (кг)'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='width',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Ширина коробки (м)'),
        ),
    ]
