# Generated by Django 5.1.3 on 2024-11-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_parcel_height_alter_parcel_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelbatch',
            name='k',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество курьеров'),
            preserve_default=False,
        ),
    ]
