# Generated by Django 5.1.3 on 2024-11-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_parcelbatch_k'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelbatch',
            name='max_cluster_size',
            field=models.PositiveIntegerField(default=0, verbose_name='Максимальное количество посылок в группе'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parcelbatch',
            name='volume',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Вместимость транспорта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parcelbatch',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Грузоподъемность транспорта'),
            preserve_default=False,
        ),
    ]
