# Generated by Django 5.1.3 on 2024-12-11 16:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_parcel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Высота коробки (м)'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='length',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Длина коробки (м)'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Вес (кг)'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='width',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Ширина коробки (м)'),
        ),
        migrations.AlterField(
            model_name='parcelbatch',
            name='k',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество курьеров'),
        ),
        migrations.AlterField(
            model_name='parcelbatch',
            name='max_cluster_size',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Максимальное количество посылок в группе'),
        ),
        migrations.AlterField(
            model_name='parcelbatch',
            name='volume',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Вместимость транспорта'),
        ),
        migrations.AlterField(
            model_name='parcelbatch',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Грузоподъемность транспорта'),
        ),
    ]
